const format_isi = "Format Isi"

export const CUSTOM_TEXT = {
  time_interval: 3000,
  size_2MB: 2097152,

  app_name: "POS",
  app_company: "Company Name",
  app_year: "2025",

  menu_home: "Home",
  menu_satuan: "Satuan",
  menu_barang: "Barang",
  menu_penjualan: "Penjualan",
  menu_links: "Links",
  menu_github: "Github",
  menu_vercel: "Vercel",

  text_tampil_data: "Tampil Data",
  text_tambah_data: "Tambah Data",
  text_ubah_data: "Ubah Data",
  text_hapus_data: "Hapus Data",
  text_detail_data: "Detail Data",
  text_cari_data: "Cari Data",
  text_loading: "Mohon Tunggu ...",
  text_informasi: "Informasi",
  text_zoom_foto: "Zoom Foto",

  info_data_kosong: "Tidak Ditemukan !",
  info_konfirmasi_hapus: "Ingin Dihapus ?",
  info_sukses_hapus: "Berhasil Dihapus",
  info_gagal_hapus: "Gagal Dihapus !",
  info_sukses_simpan: "Berhasil Disimpan",
  info_gagal_simpan: "Gagal Disimpan !",
  info_sukses_ubah: "Berhasil Diubah",
  info_gagal_ubah: "Gagal Diubah !",
  info_wajib_isi: "Harus Diisi !",
  info_wajib_pilih: "Harus Dipilih !",
  info_wajib_isi_pilih: "Harus Diisi / Dipilih !",
  info_error_redudansi: "Sudah Digunakan !",
  info_error_format: "Format File Tidak Sesuai !",
  info_error_size: "Ukuran File Tidak Sesuai !",
  info_error_server: "Server Error !",
  info_pilih_file: "Pilih / Drop File",
  info_file_label_format: "* Format File",
  info_file_label_size: "* Ukuran File Maks.",
  info_file_gambar_format: "JPG / JPEG / PNG",
  info_file_gambar_size: "2 MB",
  info_file_dokumen_format: "PDF",
  info_file_dokumen_size: "5 MB",

  button_tambah_data: "Tambah Data",
  button_refresh_data: "Refresh Data",
  button_simpan: "Simpan",
  button_ubah: "Ubah",
  button_batal: "Batal",
  button_kembali: "Kembali",
  button_ya: "Ya",
  button_tidak: "Tidak",

  tabel_aksi: "Aksi",
  tabel_pilih: "Pilih",
  tabel_satuan: "Satuan",
  tabel_kode: "Kode",
  tabel_barang: "Barang",
  tabel_harga: "Harga (Rp)",
  tabel_tanggal: "Tanggal",
  tabel_jumlah: "Jumlah",
  tabel_item: "Item",
  tabel_total: "Total (Rp)",


  form_nama_satuan: "Nama Satuan",
  form_kode_barang: "Kode Barang",
  form_nama_barang: "Nama Barang",
  form_harga_barang: "Harga Barang (Rp)",
  form_satuan_barang: "Satuan Barang",
  form_kode_penjualan: "Kode Penjualan",
  form_tanggal_penjualan: "Tanggal Penjualan",
  form_jumlah_beli: "Jumlah Beli",

  storage_satuan: "dt-satuan",
  storage_barang: "dt-barang",
  storage_penjualan_group: "dt-penjualan-group",

  storage_search_barang: "dt-search-barang",
  
  storage_selected_barang: "dt-selected-barang",
  storage_selected_penjualan: "dt-selected-penjualan",
  
  storage_detail_penjualan: "dt-detail-penjualan",
  
  storage_kode_penjualan: "kd-penjualan",
  
  storage_event_barang: "ev-barang",  
  storage_event_edit_penjualan: "ev-edit-penjualan",
  


  link_satuan_add: "/satuan/add",
  link_satuan_detail: "/satuan/detail",
  link_satuan_edit: "/satuan/edit",
  link_barang_add: "/barang/add",
  link_barang_detail: "/barang/detail",
  link_barang_edit: "/barang/edit",
  link_penjualan_add: "/penjualan/add",
  link_penjualan_detail: "/penjualan/detail",
  link_penjualan_edit: "/penjualan/edit",

  api_satuan: "/api/satuan",
  api_barang: "/api/barang",
  api_penjualan: "/api/penjualan",
  api_penjualan_group: "/api/penjualan_group",
  api_file: "/api/file",
  api_search_barang: "/api/search_barang",

  format_isi_angka: `${format_isi} : 0-9`,
  format_isi_angka_text: `${format_isi} : 0-9a-zA-Z -.,`,
  format_isi_angka_text_plus: `${format_isi} : 0-9a-zA-Z '"-.,`,
  format_isi_kode: `${format_isi} : a-zA-Z .,`,
  format_isi_nama: `${format_isi} : 0-9a-zA-Z-.`,

  dir_images: "images",
  dir_uploads: "uploads",

  file_logo: "logo.png",
  file_noimage: "noimage.png",
  file_loading: "loading.svg",
  file_404: "404.svg",
};